#애플리케이션 포트 설정
server:
  port: 8080

#Oracle 연결 설정
spring:
  datasource:
    url: jdbc:oracle:thin:@shoppingmall_high?TNS_ADMIN=/Users/kimsoohyun/Wallet_ShoppingMall
    username: ADMIN
    password: a125354861A!
    driver-class-name: oracle.jdbc.OracleDriver

  #Live Reload 기능 활성화
  devtools:
    livereload:
      enabled: true

  #Thymeleaf cache 사용 중지
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #실행되는 쿼리 콘솔 출력
        show_sql: true
        #콘솔창에 출력되는 쿼리를 가독성이 좋게 포맷팅
        format_sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect

  #logging.level:
  #쿼리에 물음표로 출력되는 바인드 파라미터 출력
  #  org.hibernate.type: trace

  servlet:
    multipart:
      #파일 한 개당 최대 사이즈
      max-file-size: 20MB
      #요청당 최대 파일 크기
      max-request-size: 100MB

##상품 이미지 업로드 경로
  itemImgLocation=/Users/kimsoohyun/Shopping_Mall_Project/item
  ##리소스 업로드 경로
  uploadPath=/Users/kimsoohyun/Shopping_Mall_Project
